using System.Diagnostics.CodeAnalysis;

namespace Scover.Dialogs;

/// <typeparam name="TSender">The type of the source of the event.</typeparam>
/// <typeparam name="TEventArgs">The type of event data generated by the event.</typeparam>
/// <remarks>Type-safe variation from <see cref="EventHandler{TEventArgs}"/>.</remarks>
/// <inheritdoc cref="EventHandler{TEventArgs}"/>
[Serializable]
[SuppressMessage("Naming", "CA1711", Justification = "Strongly-typed event handler pattern")]
public delegate void TypeEventHandler<TSender, TEventArgs>(TSender sender, TEventArgs e);

/// <typeparam name="TSender">The type of the source of the event.</typeparam>
/// <remarks>Type-safe variation from <see cref="EventHandler"/>.</remarks>
/// <inheritdoc cref="EventHandler"/>
[Serializable]
[SuppressMessage("Naming", "CA1711", Justification = "Strongly-typed event handler pattern")]
public delegate void TypeEventHandler<TSender>(TSender sender, EventArgs e);