name: Publish NuGet Package

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@master

    - name: Restore dependencies
      run: dotnet restore

    - name: Build code
      run: dotnet build

    - name: Pack NuGet Package
      run: dotnet pack --configuration Release

    - name: Publish NuGet Package
      run: dotnet nuget push **/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
