name: Publish NuGet package

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest 
    steps:

      - name: Checkout repository
        uses: actions/checkout@master
        
      - name: Setup NuGet
        uses: nuget/setup-nuget@v1
        with:
          nuget-api-key: ${{ secrets.NUGET_API_KEY }}
          nuget-version: 'latest'
          
      - name: Build and pack solution
        run: |  
          cd Dialogs
          dotnet pack -c Release -o out  
        
      - name: Push package to the NuGet registry
        run: dotnet nuget push .\Dialogs\out\*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --no-symbols --skip-duplicate
